name: Cache

on:
  schedule:
  - cron: '*/15 * * * *'

jobs:
  cache:
    runs-on: ubuntu-latest

    steps:
    - run: curl -o ethomson.gif 'https://github4life.herokuapp.com/ethomson.gif?seed=true&cachebust=true'
